In [1]:
import pandas as pd
import numpy as np

# DateFrame的创建
1. 通过Series创建
2. 通过字典来创建

In [6]:
# 通过Series创建
s1 = pd.Series([1,2,3,4,5])
s2 = pd.Series([6,7,8,9,10])
df = pd.DataFrame({"第1列：": s1, "第2列：": s2})
df

   第1列：  第2列：
0     1     6
1     2     7
2     3     8
3     4     9
4     5    10

In [41]:
# 通过字典来创建
df = pd.DataFrame(
    {
        "id": [1,2,3,4,5],
        "name": ['tom', 'jack', 'alice', 'bob', 'allen'],
        "age": [17, 17, 20, 26, 30],
        "score": [60.5, 80, 30.6, 70, 83.5]
    }, index = [1, 2, 3, 4, 5], columns = ["name", "score", "age"]
)
df

    name  score  age
1    tom   60.5   17
2   jack   80.0   17
3  alice   30.6   20
4    bob   70.0   26
5  allen   83.5   30

# DataFrame属性
1. index: 行索引
2. values:值
3. dtypes:元素类型
4. shape:形状
5. ndim:维度
6. size:元素个数
7. columns:列标签
8. loc[]:显示索引，按行列标签索引或切片
9. iloc[]:隐式索引，按行列位置索引或切片【默认下标】
10. at[]:使用行列标签访问单个元素
11. iat[]:使用行列位置访问单个元素
12. T:转置。

In [19]:
print("行索引：", df.index)
print("列标签：", df.columns)
print("值：", df.values)
print('维度：', df.ndim)
print('形状', df.shape)
print('元素个数：',df.size)
print("数据类型：\n", df.dtypes)

行索引： Index([1, 2, 3, 4, 5], dtype='int64')
列标签： Index(['name', 'score', 'age'], dtype='object')
值： [['tom' 60.5 15]
 ['jack' 80.0 17]
 ['alice' 30.6 20]
 ['bob' 70.0 26]
 ['allen' 83.5 30]]
维度： 2
形状 (5, 3)
元素个数： 15
数据类型：
 name      object
score    float64
age        int64
dtype: object

In [20]:
print(df.T)

          1     2      3     4      5
name    tom  jack  alice   bob  allen
score  60.5  80.0   30.6  70.0   83.5
age      15    17     20    26     30

In [26]:
# 获取元素
print(df.loc[2 : 4])
print('-----------------')
print(df.iloc[0])

    name  score  age
2   jack   80.0   17
3  alice   30.6   20
4    bob   70.0   26
-----------------
name      tom
score    60.5
age        15
Name: 1, dtype: object

In [28]:
# 某列
print(df.loc[:, 'name'])
print(df.iloc[:, 0])

1      tom
2     jack
3    alice
4      bob
5    allen
Name: name, dtype: object
1      tom
2     jack
3    alice
4      bob
5    allen
Name: name, dtype: object

In [33]:
# 单个元素
print(df.at[1, 'age'])
print(df.iat[3, 1])

15
70.0

In [36]:
# 获取单列数据
print(df['name'], type(df['name']))
print(df[['name']], type(df[['name']]))

1      tom
2     jack
3    alice
4      bob
5    allen
Name: name, dtype: object <class 'pandas.core.series.Series'>
    name
1    tom
2   jack
3  alice
4    bob
5  allen <class 'pandas.core.frame.DataFrame'>

In [37]:
# 查看部分数据
print(df.head(3))
print(df.tail(3))

    name  score  age
1    tom   60.5   15
2   jack   80.0   17
3  alice   30.6   20
    name  score  age
3  alice   30.6   20
4    bob   70.0   26
5  allen   83.5   30

In [38]:
df[df.score > 60]   # bool索引

    name  score  age
1    tom   60.5   15
2   jack   80.0   17
4    bob   70.0   26
5  allen   83.5   30

# DateFrame的常用方法【同Series】
1. head()/tail(): 查看前/后几行的数据，默认5行。
2. isin(): 判断元素是否在参数集合中。
3. isna(): 判断是否为缺失值(如NaN或None)。
4. sum()/mean(): 求和/求平均值。
5. min()/max(): 最小值/最大值。
6. idxmax()/idxmin(): 最大值/最小值的下标。
7. var()/std(): 方差差/标准差。
8. median(): 中位数。【不包含NaN】
9. mode(): 众数(可返回多个)。
10. quantile(q): 分位数，q取0-1之间。
11. describe(): 常见统计信息(count, mean, std, min, 25%, 50%, 75%, max)
12. value_counts():每个唯一值的出现次数。
13. count(): 非缺失值的数量。
14. duplicated(): 是否重复。
15. sample(): 随机抽样。
16. sort_index(): 按索引排序。
17. sort_values(): 按值排序。
18. replace(): 替换值。
19. nlargest()： 返回某列最大的n条数据。
20. nsmallest()：返回某列最小的n条数据。

In [40]:
print(df['score'].sum())
df.sum()

324.6

name     tomjackaliceboballen
score                   324.6
age                       108
dtype: object

In [44]:
print(df.score.max())
print(df.name.min())
print(df.score.mean())
print(df.score.median())
print(df.score.var())
print(df.score.std())
print(df.age.mode())

83.5
alice
64.92
70.0
448.957
21.188605428390044
0    17
Name: age, dtype: int64

In [45]:
print(df.describe())

           score        age
count   5.000000   5.000000
mean   64.920000  22.000000
std    21.188605   5.787918
min    30.600000  17.000000
25%    60.500000  17.000000
50%    70.000000  20.000000
75%    80.000000  26.000000
max    83.500000  30.000000

In [46]:
print(df.count())
print(df.value_counts())

name     5
score    5
age      5
dtype: int64
name   score  age
alice  30.6   20     1
allen  83.5   30     1
bob    70.0   26     1
jack   80.0   17     1
tom    60.5   17     1
Name: count, dtype: int64

In [47]:
print(df.sample(2))

   name  score  age
4   bob   70.0   26
2  jack   80.0   17

In [48]:
df.cumsum()     # 累积和

                   name  score  age
1                   tom   60.5   17
2               tomjack  140.5   34
3          tomjackalice  171.1   54
4       tomjackalicebob  241.1   80
5  tomjackaliceboballen  324.6  110

In [51]:
df.cummax()

  name  score  age
1  tom   60.5   17
2  tom   80.0   17
3  tom   80.0   20
4  tom   80.0   26
5  tom   83.5   30

In [50]:
df.cummin()

    name  score  age
1    tom   60.5   17
2   jack   60.5   17
3  alice   30.6   17
4  alice   30.6   17
5  alice   30.6   17

In [53]:
print(df.sort_index(ascending=False))

    name  score  age
5  allen   83.5   30
4    bob   70.0   26
3  alice   30.6   20
2   jack   80.0   17
1    tom   60.5   17

In [54]:
print(df.sort_values(by=['score', 'age'], ascending=[True, False]))

    name  score  age
3  alice   30.6   20
1    tom   60.5   17
4    bob   70.0   26
2   jack   80.0   17
5  allen   83.5   30

In [56]:
df.nlargest(2, columns=['score', 'age'])

    name  score  age
5  allen   83.5   30
2   jack   80.0   17