In [1]:
import pandas as pd
import numpy as np
from asyncssh import scp

In [2]:
"""
案例 1: 学生成绩分析
场景：某班级的学生成绩数据如下，请完成以下任务：
1. 计算每位学生的总分和平均分。
2. 找出数学成绩高于90分或英语成绩高于85分的学生。
3. 按总分从高到低排序，并输出前3名学生。

data = {
    '姓名': ['张三', '李四', '王五', '赵六', '钱七'],
    '数学': [85, 92, 78, 88, 95],
    '英语': [90, 88, 85, 92, 80],
    '物理': [75, 80, 88, 85, 90]
}
"""

"\n案例 1: 学生成绩分析\n场景：某班级的学生成绩数据如下，请完成以下任务：\n1. 计算每位学生的总分和平均分。\n2. 找出数学成绩高于90分或英语成绩高于85分的学生。\n3. 按总分从高到低排序，并输出前3名学生。\n\ndata = {\n    '姓名': ['张三', '李四', '王五', '赵六', '钱七'],\n    '数学': [85, 92, 78, 88, 95],\n    '英语': [90, 88, 85, 92, 80],\n    '物理': [75, 80, 88, 85, 90]\n}\n"

In [10]:
data = {
    '姓名': ['张三', '李四', '王五', '赵六', '钱七'],
    '数学': [85, 92, 78, 88, 95],
    '英语': [90, 88, 85, 92, 80],
    '物理': [75, 80, 88, 85, 90]
}

scores = pd.DataFrame(data)
scores

   姓名  数学  英语  物理
0  张三  85  90  75
1  李四  92  88  80
2  王五  78  85  88
3  赵六  88  92  85
4  钱七  95  80  90

In [27]:
# 计算学生的总分数和平均分
scores['all'] = scores[['数学', '英语', '物理']].sum(axis = 1)    # 换轴
scores['mean'] = scores[['数学', '英语', '物理']].mean(axis = 1)

# 找出数学成绩高于90分或英语成绩高于85分的学生
print(scores[(scores['数学'] > 90) | (scores['英语'] > 85)].姓名)
# 按总分从高到低排序，并输出前3名学生
print(scores.sort_values('all', ascending=False, ))
print(scores.nlargest(3, ['all']).姓名)
scores

0    张三
1    李四
3    赵六
4    钱七
Name: 姓名, dtype: object
   姓名  数学  英语  物理  all       mean
3  赵六  88  92  85  265  88.333333
4  钱七  95  80  90  265  88.333333
1  李四  92  88  80  260  86.666667
2  王五  78  85  88  251  83.666667
0  张三  85  90  75  250  83.333333
3    赵六
4    钱七
1    李四
Name: 姓名, dtype: object

   姓名  数学  英语  物理  all       mean
0  张三  85  90  75  250  83.333333
1  李四  92  88  80  260  86.666667
2  王五  78  85  88  251  83.666667
3  赵六  88  92  85  265  88.333333
4  钱七  95  80  90  265  88.333333

In [28]:
"""
案例 2: 销售数据分析
场景：某公司销售数据如下，请完成以下任务：
1. 计算每种产品的总销售额（销售额 = 单价 * 销量）。
2. 找出销售额最高的产品。
3. 按销售额从高到低排序，并输出所有产品信息。
"""

'\n案例 2: 销售数据分析\n场景：某公司销售数据如下，请完成以下任务：\n1. 计算每种产品的总销售额（销售额 = 单价 * 销量）。\n2. 找出销售额最高的产品。\n3. 按销售额从高到低排序，并输出所有产品信息。\n'

In [41]:
data = {
    '产品名称': ['A', 'B', 'C', 'D'],
    '单价': [100, 150, 200, 120],
    '销量': [50, 30, 20, 40]
}

df = pd.DataFrame(data)
df

  产品名称   单价  销量
0    A  100  50
1    B  150  30
2    C  200  20
3    D  120  40

In [52]:
# 1. 计算每种产品的总销售额（销售额 = 单价 * 销量）。
df['总销售额'] = df['单价'] * df['销量']
# 2. 找出销售额最高的产品。
print(df.nlargest(1, columns=['总销售额']).产品名称)
# 3. 按销售额从高到低排序，并输出所有产品信息。
print(df.sort_values('总销售额', ascending=False, ))

0    A
Name: 产品名称, dtype: object
  产品名称   单价  销量   销售额  总销售额
0    A  100  50  5000  5000
3    D  120  40  4800  4800
1    B  150  30  4500  4500
2    C  200  20  4000  4000

In [53]:
"""
案例 3： 电商用户行为分析
场景： 某电商平台的用户行为数据如下，请完成以下任务：
1. 计算每位用户的总消费金额（消费金额 = 商品单价 * 购买数量）
2. 找出消费金额最高的用户，并输出其所有信息
3. 计算所有用户的平均消费金额（保存2位小数）
4. 统计电子产品的总购买数量
"""

'\n案例 3： 电商用户行为分析\n场景： 某电商平台的用户行为数据如下，请完成以下任务：\n1. 计算每位用户的总消费金额（消费金额 = 商品单价 * 购买数量）\n2. 找出消费金额最高的用户，并输出其所有信息\n3. 计算所有用户的平均消费金额（保存2位小数）\n4. 统计电子产品的总购买数量\n'

In [54]:
data = {
    '用户ID': [101, 102, 103, 104, 105],
    '用户名': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    '商品类别': ['电子产品', '服饰', '电子产品', '家居', '服饰'],
    '商品单价': [1200, 300, 800, 150, 200],
    '购买数量': [1, 3, 2, 5, 5]
}

df = pd.DataFrame(data)

In [63]:
# 1. 计算每位用户的总消费金额（消费金额 = 商品单价 * 购买数量）
df['总消费金额'] = df['商品单价'] * df['购买数量']
# 2. 找出消费金额最高的用户，并输出其所有信息
print(df.nlargest(1, '总消费金额'))
# 3. 计算所有用户的平均消费金额（保存2位小数）
print(df['总消费金额'].mean())
# 4. 统计电子产品的总购买数量
print(df[df['商品类别'] == '电子产品']['购买数量'].sum())
df

   用户ID      用户名  商品类别  商品单价  购买数量  总消费金额  平均消费金额
2   103  Charlie  电子产品   800     2   1600   800.0
1090.0
3

   用户ID      用户名  商品类别  商品单价  购买数量  总消费金额  平均消费金额
0   101    Alice  电子产品  1200     1   1200  1200.0
1   102      Bob    服饰   300     3    900   300.0
2   103  Charlie  电子产品   800     2   1600   800.0
3   104    David    家居   150     5    750   150.0
4   105      Eve    服饰   200     5   1000   200.0